### ISSUE TITLE
管理员账号和密码

### ISSUE THREAD

**Issue by laoli19971127** [xianzhixianzhixian/warehouse-web#2]
不能登录进去，无法修改用户密码

**Comment by xianzhixianzhixian** [comment]
自己看源码吧


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------发件人： laoli19971127 <notifications@github.com> 日期: 2019/4/29  11:52  (GMT+08:00) 收件人： xianzhixianzhixian/warehouse-web <warehouse-web@noreply.github.com> 抄送： Subscribed <subscribed@noreply.github.com> 主题： [xianzhixianzhixian/warehouse-web] 管理员账号和密码 (#2) 
不能登录进去，无法修改用户密码



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xianzhixianzhixian/warehouse-web","title":"xianzhixianzhixian/warehouse-web","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/xianzhixianzhixian/warehouse-web"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"管理员账号和密码 (#2)"}],"action":{"name":"View Issue","url":"https://github.com/xianzhixianzhixian/warehouse-web/issues/2"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/xianzhixianzhixian/warehouse-web/issues/2",

"url": "https://github.com/xianzhixianzhixian/warehouse-web/issues/2",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by laoli19971127** [comment]
没有找到管理员密码和账号






------------------ 原始邮件 ------------------
发件人: "樊先知樊先知"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 下午4:09
收件人: "xianzhixianzhixian/warehouse-web"<warehouse-web@noreply.github.com>;
抄送：  “1721683536”<1721683536@qq.com>; “作者”<author@noreply.github.com>;
主题: Re: [xianzhixianzhixian/warehouse-web] 管理员账号和密码 (#2)



自己看源码吧
 
 
 发送自我的三星盖乐世智能手机。
 -------- 原始信息 --------发件人： laoli19971127 <notifications@github.com> 日期: 2019/4/29  11:52  (GMT+08:00) 收件人： xianzhixianzhixian/warehouse-web <warehouse-web@noreply.github.com> 抄送： Subscribed <subscribed@noreply.github.com> 主题： [xianzhixianzhixian/warehouse-web] 管理员账号和密码 (#2) 
 不能登录进去，无法修改用户密码
 
 
 
 —
 You are receiving this because you are subscribed to this thread.
 Reply to this email directly, view it on GitHub, or mute the thread.
 
 { “API_VERSION”： “1.0”， “出版者”：{ “API_KEY”： “05dde50f1d1a384dd78767c55493e4bb”， “名称”： “GitHub的”}， “实体”：{ “external_key”： “的github / xianzhixianzhixian /仓库的web”， “title”：“xianzhixianzhixian / warehouse-web”，“subtitle”：“GitHub repository”，“main_image_url”：“https：//github.githubassets.com/images/email/message_cards/header.png”，“avatar_image_url” ：“https://github.githubassets.com/images/email/message_cards/avatar.png”，“action”：{“name”：“在GitHub中打开”，“url”：“https：//github.com / xianzhixianzhixian /仓库的web “}}，”更新“：{”片段“：[{”图标“：”描述”， “消息”：“管理员账号和密码（＃2）”}]，“行动”：{“名称”：“查看问题”，“网址”：“https://github.com/xianzhixianzhixian/warehouse-web/issues/2 “}}} 
 
 [ 
 
 { 
 
 ” 
 
 @ context“：” http://schema.org“，”@ type“：”EmailMessage“，
 
 ”potentialAction“：{
 
 “@type”：“ViewAction”，
 
 “target”：“https：//github.com/xianzhixianzhixian/warehouse-web/issues/2”，
 
 “url”：“https：//github.com/xianzhixianzhixian/warehouse- web / issues / 2“，
 
 ”name“：”查看问题“ 
 
 }，
 
 ”描述“：”在GitHub上查看此问题“，
 
 ”发布者“：{ 
 
 ”@ type“：”组织“，
 
 ”名称“：”GitHub“ ，
 
 “url”：“https：//github.com” 
 
 } 
 
 } 
 
 ]
   
- 
您收到此消息是因为您创作了该帖子。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by laoli19971127** [comment]
这是什么意思啊，兄弟






------------------ 原始邮件 ------------------
发件人: "樊先知樊先知"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 下午4:54
收件人: "xianzhixianzhixian/warehouse-web"<warehouse-web@noreply.github.com>;
抄送: "1721683536"<1721683536@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xianzhixianzhixian/warehouse-web] 管理员账号和密码 (#2)




Closed #2.
